name: CI-CD
on:
  workflow_dispatch:

  push:
    branches:
      - **
      
jobs:
  print-commits:
    runs-on: ubuntu-latest
    steps:

      - name: get_increment_strategies
        id: get_increment_strategies
        run: |
          echo ${{github.event.commits[0].message}}
          echo ${{github.event.commits[-1].message}}
