name: CI-CD
on:
  workflow_dispatch:

  push:
    branches:
      - '**'
      
jobs:
  print-commits:
    runs-on: ubuntu-latest
    steps:

      - name: print_commits
        id: print_commits
        run: |
          echo ${{github.event.commits[0].message}}
          echo ${{github.event.head_commit.message}}
          echo ${{github.event.commits[-1].message}}
          echo ${{github.event.commits[-2].message}}
          echo ${{github.event.commits}}
